"""add intake to MedicalInterview

Revision ID: 17abeee4a6d0
Revises: e58de1c4a25b
Create Date: 2025-12-15 11:29:15.325887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17abeee4a6d0'
down_revision: Union[str, Sequence[str], None] = 'e58de1c4a25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_interviews', sa.Column('intake', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interviews', 'intake')
    # ### end Alembic commands ###
