"""Added created_at to MedicalInterview

Revision ID: 3f49537114f0
Revises: 83e87652f26c
Create Date: 2025-12-12 20:02:03.688654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f49537114f0'
down_revision: Union[str, Sequence[str], None] = '83e87652f26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_interviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interviews', 'created_at')
    # ### end Alembic commands ###
