"""Update appointment table

Revision ID: 40f57f461f36
Revises: 482392f0751b
Create Date: 2025-12-14 21:33:13.891455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f57f461f36'
down_revision: Union[str, Sequence[str], None] = '482392f0751b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'first_name')
    op.drop_column('appointments', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
