"""Add user table

Revision ID: 482392f0751b
Revises: 3f49537114f0
Create Date: 2025-12-14 21:30:38.640711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482392f0751b'
down_revision: Union[str, Sequence[str], None] = '3f49537114f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'patient_id')
    op.drop_table('patients')
    # ### end Alembic commands ###
