"""delete unnecessary columns

Revision ID: a7cf1df20f78
Revises: 17abeee4a6d0
Create Date: 2025-12-16 17:00:20.151473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cf1df20f78'
down_revision: Union[str, Sequence[str], None] = '17abeee4a6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interviews', 'duration')
    op.drop_column('medical_interviews', 'current_medications')
    op.drop_column('medical_interviews', 'visit_reason')
    op.drop_column('medical_interviews', 'initial_findings')
    op.drop_column('medical_interviews', 'symptoms')
    op.drop_column('medical_interviews', 'allergies')
    op.drop_column('medical_interviews', 'severity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_interviews', sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('initial_findings', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('visit_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('current_medications', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_interviews', sa.Column('duration', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
