"""add status to MedicalInterview

Revision ID: bd0cf15617b3
Revises: a7cf1df20f78
Create Date: 2025-12-16 20:56:34.360601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0cf15617b3'
down_revision: Union[str, Sequence[str], None] = 'a7cf1df20f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

interview_status = sa.Enum('DRAFT', 'COMPLETED', name='interview_status')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    interview_status.create(bind, checkfirst=True)
    op.add_column('medical_interviews', sa.Column('status', interview_status, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interviews', 'status')
    # ### end Alembic commands ###
