"""Add user table

Revision ID: e58de1c4a25b
Revises: 40f57f461f36
Create Date: 2025-12-14 21:33:45.903270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58de1c4a25b'
down_revision: Union[str, Sequence[str], None] = '40f57f461f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
